version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    depends_on:
      - backend
      - database

  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=mipassword
      - DB_NAME=miapp
    command: >
      bash -c "npm install && npm start"
    restart: always
    depends_on:
      - database

  database:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=mipassword
      - MYSQL_DATABASE=miapp
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: