global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:3001"]

  - job_name: "database"
    static_configs:
      - targets: ["database:9104"]

  - job_name: "web"
    static_configs:
      - targets: ["web:80"]
